// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// f_y_hat_epnechikov
NumericVector f_y_hat_epnechikov(NumericVector Y, NumericVector y, double h);
RcppExport SEXP _cic_f_y_hat_epnechikov(SEXP YSEXP, SEXP ySEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(f_y_hat_epnechikov(Y, y, h));
    return rcpp_result_gen;
END_RCPP
}
// rect_counts_rcpp
IntegerVector rect_counts_rcpp(NumericVector X_sorted, NumericVector x_eval, NumericVector h_vals);
RcppExport SEXP _cic_rect_counts_rcpp(SEXP X_sortedSEXP, SEXP x_evalSEXP, SEXP h_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X_sorted(X_sortedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_eval(x_evalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h_vals(h_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(rect_counts_rcpp(X_sorted, x_eval, h_vals));
    return rcpp_result_gen;
END_RCPP
}
// counts_to_density
NumericVector counts_to_density(IntegerVector counts, NumericVector h_vals, int n);
RcppExport SEXP _cic_counts_to_density(SEXP countsSEXP, SEXP h_valsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h_vals(h_valsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(counts_to_density(counts, h_vals, n));
    return rcpp_result_gen;
END_RCPP
}
// boot_core
NumericVector boot_core(NumericVector Ys, NumericVector Xs, NumericVector Zs, int B);
RcppExport SEXP _cic_boot_core(SEXP YsSEXP, SEXP XsSEXP, SEXP ZsSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type Ys(YsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xs(XsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Zs(ZsSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_core(Ys, Xs, Zs, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cic_f_y_hat_epnechikov", (DL_FUNC) &_cic_f_y_hat_epnechikov, 3},
    {"_cic_rect_counts_rcpp", (DL_FUNC) &_cic_rect_counts_rcpp, 3},
    {"_cic_counts_to_density", (DL_FUNC) &_cic_counts_to_density, 3},
    {"_cic_boot_core", (DL_FUNC) &_cic_boot_core, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_cic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
